apiVersion: "serving.kubeflow.org/v1beta1"
kind: "InferenceService"
metadata:
  name: "artserver"
spec:
  predictor:
    containers:
    - name: predictor
      image: ibmandrewbutler/art-server:sklearn-mnist-v2
      imagePullPolicy: Always
  explainer:
    art:
      type: SquareAttack
      config:
        nb_classes: "10"
